"""Dynamometer card fault classification with a 1D convolutional network.

Six operational states of a sucker rod pump are distinguished from the
reconstructed downhole card:

===========================  ==========================================
Label                        Physical signature
===========================  ==========================================
``NORMAL_FULL_BARREL``       Full-barrel parallelogram, 100% fillage.
``FLUID_POUND``              Inflow below pump displacement: the load
                             collapses over the un-filled part of the
                             upstroke and a late impact follows.
``ROD_FLOATING``             Buoyant viscous drag on the downstroke drives
                             the load below rod weight, into compression.
``GAS_INTERFERENCE``         A compressed gas cap cushions the card: small
                             amplitude, rounded corners, high ripple.
``PUMP_TAGGING``             The plunger meets a stop, giving a load spike
                             at the end of the downstroke.
``UNANCHORED_TUBING``        Skewed parallelogram: the load extrema are
                             displaced from top and bottom dead centre.
===========================  ==========================================

The network is a residual 1D CNN over the ``(position, load)`` sequence, which
is normalised to a fixed-length resampling so that cards from different SPM
and stroke settings share one representation.  Training data is generated by a
parametric forward model of the surface card, so the routine on
:func:`ensure_weights` can bootstrap the network from first principles when no
cached weights are present.
"""

from __future__ import annotations

import math
import os
from dataclasses import dataclass
from enum import Enum
from pathlib import Path
from typing import Dict, List, Optional, Sequence, Tuple

import numpy as np

from backend.app.core.config import PUMPING_UNIT, THRESHOLDS

__all__ = [
    "CardLabel",
    "CARD_LABELS",
    "DynoCardNet",
    "DynoCardClassifier",
    "synthesize_card",
    "normalise_card",
    "analytic_diagnosis",
    "build_training_set",
    "ensure_weights",
    "card_features",
]

#: Number of samples in the normalised card representation.
CARD_LENGTH = 128
#: Number of crank cycles generated by the parametric card model.
SAMPLES_PER_CARD = 512


class CardLabel(str, Enum):
    """Operational states recognised by the classifier."""

    NORMAL_FULL_BARREL = "NORMAL_FULL_BARREL"
    FLUID_POUND = "FLUID_POUND"
    ROD_FLOATING = "ROD_FLOATING"
    GAS_INTERFERENCE = "GAS_INTERFERENCE"
    PUMP_TAGGING = "PUMP_TAGGING"
    UNANCHORED_TUBING = "UNANCHORED_TUBING"


CARD_LABELS: Tuple[CardLabel, ...] = tuple(CardLabel)
LABEL_INDEX: Dict[CardLabel, int] = {label: i for i, label in enumerate(CARD_LABELS)}


# ---------------------------------------------------------------------------
# Parametric card generator
# ---------------------------------------------------------------------------


def synthesize_card(
    label: CardLabel,
    rod_weight_n: float = 21937.6,
    fluid_load_n: float = 26000.0,
    stroke_m: float = PUMPING_UNIT.nominal_stroke_m,
    fillage: float = 1.0,
    samples: int = SAMPLES_PER_CARD,
    noise_fraction: float = 0.01,
    seed: Optional[int] = None,
    valve_width_fraction: float = 0.25,
) -> Tuple[np.ndarray, np.ndarray]:
    r"""Generate a synthetic surface dynamometer card for ``label``.

    The card is built from the standard sucker rod pump construction.  The
    polished rod position over a crank cycle is, to a very good approximation,
    sinusoidal,

    .. math:: x(\theta) = \frac{L_s}{2}(1 - \cos\theta),

    and the surface load is the rod weight plus the fluid column load.  On the
    upstroke the pump fills and the fluid load grows roughly linearly with
    position, which is what produces the familiar parallelogram; on the
    downstroke the column unloads along the same line.

    Parameters
    ----------
    label
        Target state, which selects the deformation applied to the ideal card.
    rod_weight_n
        Weight of the rod string, N.
    fluid_load_n
        Load of a full fluid column, N.
    stroke_m
        Stroke length, m.
    fillage
        Pump fillage in [0, 1]; below 1 the barrel does not fill and the
        classic fluid pound develops.
    samples
        Number of samples in the returned card.
    noise_fraction
        Standard deviation of the additive load noise, as a fraction of the
        load span.
    seed
        Optional seed for the noise, for reproducible training sets.
    valve_width_fraction
        Width of the card loop as a fraction of the full fluid load, i.e. how
        much heavier the upstroke is than the downstroke.  Zero produces a
        single line, which is not what a real pump traces; the working range is
        roughly 0.10 to 0.45.

    Returns
    -------
    (position_m, load_n)
        The card, as float arrays of length ``samples``.
    """
    if samples < 32:
        raise ValueError("at least 32 samples are required")
    if not 0.0 < fillage <= 1.0:
        raise ValueError("fillage must lie in (0, 1]")
    if rod_weight_n <= 0.0 or fluid_load_n <= 0.0:
        raise ValueError("rod weight and fluid load must be positive")
    if valve_width_fraction < 0.0:
        raise ValueError("valve_width_fraction must be non-negative")

    rng = np.random.default_rng(seed)
    crank = np.linspace(0.0, 2.0 * math.pi, samples, endpoint=False)
    # Polished rod position: 0 at bottom dead centre, stroke at top dead centre.
    position = 0.5 * stroke_m * (1.0 - np.cos(crank))
    normalised = position / stroke_m          # 0..1 across the stroke
    upstroke = crank < math.pi                 # position rising
    load = np.full(samples, rod_weight_n, dtype=float)

    # Travelling-valve differential, applied to every label.  The standing valve
    # admits fluid while the plunger rises and the travelling valve expels it
    # while the plunger falls, so the two strokes never carry the same column
    # weight.  This width is what makes the card a *parallelogram* rather than a
    # single line: without it the load is a pure function of position and both
    # strokes trace the same curve.  It scales with the volume swept, so the
    # width is zero at bottom dead centre and widest at top dead centre.
    valve_width = valve_width_fraction * fluid_load_n * np.clip(normalised, 0.0, 1.0)
    load += np.where(upstroke, valve_width, -valve_width)

    if label is CardLabel.NORMAL_FULL_BARREL:
        # Full barrel: the fluid load follows the swept volume exactly and the
        # loop keeps a constant width, so the card is a straight-sided
        # parallelogram.  This is the reference shape every other fault
        # deforms.
        load += fluid_load_n * np.clip(normalised, 0.0, 1.0)

    elif label is CardLabel.FLUID_POUND:
        # The plunger displaces more fluid than the formation supplies, so after
        # the barrel has filled at ``fillage`` of the stroke the column can no
        # longer support the rod and the load *falls* while the plunger is still
        # rising.  A load that decreases with rising position is the defining
        # fluid-pound signature.
        filled = np.clip(normalised / max(fillage, 1e-6), 0.0, 1.0)
        drained = np.where(
            upstroke,
            np.clip((normalised - fillage) / max(1.0 - fillage, 1e-6), 0.0, 1.0),
            0.0,
        )
        load += fluid_load_n * (filled - 0.95 * drained)

    elif label is CardLabel.ROD_FLOATING:
        # Buoyant viscous drag on the downstroke: the descending rod column is
        # buoyed by the fluid, so the surface load is depressed through the
        # middle of the downstroke and can pass below the rod weight.  The drag
        # bump is a genuine function of crank angle, not a phase mask, so it
        # varies *along* the downstroke.
        load += fluid_load_n * np.clip(normalised, 0.0, 1.0)
        drag_bump = np.exp(-(((crank - 1.55 * math.pi) / 0.42) ** 2))
        load -= 1.15 * fluid_load_n * drag_bump

    elif label is CardLabel.GAS_INTERFERENCE:
        # A compressed gas cap is compressed further as the plunger enters, so
        # it cushions the load: the span collapses and the trace gains ripple.
        cushion = 0.45 + 0.55 * np.clip(normalised, 0.0, 1.0)
        load += fluid_load_n * cushion * np.clip(normalised, 0.0, 1.0)
        load += fluid_load_n * 0.16 * np.sin(11.0 * crank)

    elif label is CardLabel.PUMP_TAGGING:
        # The plunger meets a mechanical stop at the end of the downstroke.
        load += fluid_load_n * np.clip(normalised, 0.0, 1.0)
        impact = np.exp(-(((crank - 1.97 * math.pi) / 0.045) ** 2))
        load += 1.30 * fluid_load_n * impact

    elif label is CardLabel.UNANCHORED_TUBING:
        # The tubing is not anchored, so the load extrema lag the dead centres
        # by a fixed crank offset: a skewed parallelogram.
        lagged = np.mod(crank - 1.05, 2.0 * math.pi)
        skewed = np.clip(0.5 * (1.0 - np.cos(lagged)), 0.0, 1.0)
        load += fluid_load_n * skewed

    else:  # pragma: no cover - exhaustive over the enum
        raise ValueError(f"unknown card label {label!r}")

    if noise_fraction > 0.0:
        span = float(np.max(load) - np.min(load)) or 1.0
        load = load + rng.normal(0.0, noise_fraction * span, samples)

    return position, load


def build_training_set(
    samples_per_label: int = 900,
    seed: int = 26120,
    samples: int = SAMPLES_PER_CARD,
    damping_rates: Optional[Sequence[float]] = None,
) -> Tuple[np.ndarray, np.ndarray]:
    """Generate a labelled training set from the parametric card model.

    Each class is drawn over a randomised operating envelope (stroke, fillage,
    noise, rod and fluid loads) so the network cannot latch onto a single
    amplitude.

    The synthetic surface cards are passed through the Gibbs solver with varying
    damping rates to produce downhole cards, matching the inference-time
    distribution shift caused by rod-string damping across different reservoir
    temperatures.

    Returns
    -------
    (inputs, targets)
        ``inputs`` has shape ``(n, 2, CARD_LENGTH)`` (position and load
        channels, normalised); ``targets`` has shape ``(n,)`` of int64 labels.
    """
    # Import here to avoid circular dependency at module load time
    from backend.app.physics.gibbs_solver import GibbsSolver, baghewala_rod_string

    if damping_rates is None:
        # Range of damping rates covering cool (high viscosity) to hot (low viscosity)
        damping_rates = [0.05, 0.10, 0.15, 0.20, 0.25, 0.30]

    rng = np.random.default_rng(seed)
    inputs: List[np.ndarray] = []
    targets: List[int] = []
    rod = baghewala_rod_string()
    for label in CARD_LABELS:
        for _ in range(samples_per_label):
            stroke = float(rng.uniform(1.8, 3.0))
            if label is CardLabel.FLUID_POUND:
                fillage = float(rng.uniform(0.35, 0.85))
            elif label is CardLabel.ROD_FLOATING:
                fillage = float(rng.uniform(0.85, 1.0))
            else:
                fillage = float(rng.uniform(0.92, 1.0))
            rod_weight = float(rng.uniform(15000.0, 30000.0))
            fluid_load = float(rng.uniform(12000.0, 45000.0))
            noise = float(rng.uniform(0.002, 0.03))
            # The card loop width, spanning the plausible range for the
            # travelling-valve differential.  The network must learn every
            # width, not one, or it will latch onto an amplitude instead of a
            # shape and misread a well with a different valve as faulty.
            valve_width_fraction = float(rng.uniform(0.10, 0.45))
            position, load = synthesize_card(
                label,
                rod_weight_n=rod_weight,
                fluid_load_n=fluid_load,
                stroke_m=stroke,
                fillage=fillage,
                samples=samples,
                noise_fraction=noise,
                seed=int(rng.integers(0, 2**31 - 1)),
                valve_width_fraction=valve_width_fraction,
            )
            # Reconstruct to downhole card with random damping to match inference distribution
            damping = float(rng.choice(damping_rates))
            solver = GibbsSolver(rod=rod, segments=40, damping_rate_s=damping)
            card = solver.solve(
                surface_position_m=position,
                surface_load_n=load,
                duration_s=60.0 / 9.0,  # nominal SPM cycle duration
            )
            normalised = normalise_card(card.position_m, card.load_n, samples=CARD_LENGTH)
            inputs.append(normalised)
            targets.append(LABEL_INDEX[label])
    return np.asarray(inputs, dtype=np.float32), np.asarray(targets, dtype=np.int64)


def normalise_card(
    position_m: Sequence[float], load_n: Sequence[float], samples: int = CARD_LENGTH
) -> np.ndarray:
    """Resample and normalise a card into a ``(2, samples)`` network input.

    Position is scaled to ``[-1, 1]`` over the observed stroke and load to
    zero mean and unit standard deviation, so the network sees shape rather
    than absolute magnitude.

    Raises
    ------
    ValueError
        If the card is shorter than ``samples`` or is not finite.
    """
    position = np.asarray(position_m, dtype=float)
    load = np.asarray(load_n, dtype=float)
    if position.ndim != 1 or load.ndim != 1:
        raise ValueError("card inputs must be one-dimensional")
    if len(position) != len(load):
        raise ValueError("position and load must have the same length")
    if len(position) < 8:
        raise ValueError("at least eight card samples are required")
    if not np.all(np.isfinite(position)) or not np.all(np.isfinite(load)):
        raise ValueError("card contains non-finite values")

    source = np.linspace(0.0, 1.0, len(position))
    target = np.linspace(0.0, 1.0, samples)
    resampled_position = np.interp(target, source, position)
    resampled_load = np.interp(target, source, load)

    stroke = float(np.max(resampled_position) - np.min(resampled_position))
    if stroke <= 0.0:
        raise ValueError("card has zero stroke")
    centre = 0.5 * (float(np.max(resampled_position)) + float(np.min(resampled_position)))
    scaled_position = (resampled_position - centre) / (0.5 * stroke)

    spread = float(np.std(resampled_load))
    if spread <= 0.0:
        spread = 1.0
    scaled_load = (resampled_load - float(np.mean(resampled_load))) / spread

    return np.stack([scaled_position, scaled_load]).astype(np.float32)


# ---------------------------------------------------------------------------
# Interpretable geometric features
# ---------------------------------------------------------------------------


def _width_profile_residual(
    normalised: np.ndarray,
    load: np.ndarray,
    rising: np.ndarray,
    falling: np.ndarray,
    span: float,
    bins: int = 16,
) -> float:
    r"""Departure of the card loop from a constant-width parallelogram.

    The card is divided into ``bins`` slices of plunger position.  In each
    slice that contains samples from both strokes, the mean downstroke load less
    the mean upstroke load gives the local width :math:`w(u)`.  A healthy card
    has :math:`w` close to a straight line in :math:`u`, because the travelling
    valve loads the two strokes by about the same amount everywhere; rod float
    adds a localised mid-downstroke depression, which bows the profile.

    The returned value is the RMS departure from the best-fit line, normalised by
    the load span so it is independent of amplitude.

    Binning is on position rather than on time because the Gibbs solver re-phases
    the card, so sample order is arbitrary but matched positions are not.  Bins
    that fall on a turnaround and contain only one stroke are skipped, and a card
    with too few usable bins returns ``0.0`` rather than raising.
    """
    if span <= 0.0:
        return 0.0
    # ``rising``/``falling`` are differences, so they index the interval
    # [i, i+1]; attribute each to its left-hand sample's position.
    up_mask = np.zeros_like(normalised, dtype=bool)
    down_mask = np.zeros_like(normalised, dtype=bool)
    up_mask[:-1] |= rising
    down_mask[:-1] |= falling
    up_mask[1:] |= rising
    down_mask[1:] |= falling

    centres: List[float] = []
    widths: List[float] = []
    for index in range(bins):
        centre = (index + 0.5) / bins
        selection = np.abs(normalised - centre) < (0.6 / bins)
        up = selection & up_mask
        down = selection & down_mask
        if not up.any() or not down.any():
            continue
        centres.append(centre)
        widths.append(float(np.mean(load[down]) - np.mean(load[up])))

    if len(centres) < 4:
        return 0.0
    x = np.asarray(centres, dtype=float)
    y = np.asarray(widths, dtype=float)
    slope, intercept = np.polyfit(x, y, 1)
    residual = y - (slope * x + intercept)
    return float(np.sqrt(np.mean(residual**2)) / span)


def card_features(position_m: Sequence[float], load_n: Sequence[float]) -> Dict[str, float]:
    """Geometric features of a card, used by the analytic cross-check.

    The features encode the four physical diagnostics an analyst reads off a
    card:

    ``upstroke_reversal``
        Fraction of the upstroke over which the load *falls* while the plunger
        rises.  Physically impossible in steady pumping, and the definitive
        fluid-pound signature.
    ``downstroke_asymmetry``
        Departure of the card loop from a *constant-width* parallelogram,
        normalised by the load span.  A healthy card is a loop of roughly
        constant width -- the travelling valve makes the upstroke heavier than
        the downstroke by about the same amount at every position -- so its
        width profile is straight.  Buoyant drag on the downstroke is instead a
        localised depression at mid-downstroke, so the width profile is bumpy.
        This is the rod-float signature.

        The name is retained from the earlier mean-difference definition for
        contract compatibility: the ten feature keys are pinned by
        ``backend/tests/test_api_stream.py::FEATURE_KEYS`` and read by name in
        ``frontend/src/components/DynoCardCanvas.tsx``.  The *meaning* changed
        when the generator was corrected to emit a real parallelogram, because
        the mean difference alone cannot separate a healthy loop's width from a
        floating rod's depression.
    ``tail_spike``
        Load excess at the end of the downstroke, i.e. a mechanical impact.
    ``linearity``
        RMS departure of the card from a straight-sided parallelogram.  A
        cushioning gas cap rounds the card, so a non-parallelogram shape with
        none of the specific faults present is gas interference.
    ``skew``
        Displacement of the load maximum from top dead centre, which is the
        unanchored-tubing signature.
    """
    position = np.asarray(position_m, dtype=float)
    load = np.asarray(load_n, dtype=float)
    if position.ndim != 1 or load.ndim != 1 or len(position) != len(load):
        raise ValueError("position and load must be one-dimensional and equal length")
    if len(position) < 8:
        raise ValueError("at least eight card samples are required")

    stroke = float(np.max(position) - np.min(position))
    if stroke <= 0.0:
        raise ValueError("card has zero stroke")
    normalised = (position - float(np.min(position))) / stroke
    load_min = float(np.min(load))
    load_max = float(np.max(load))
    span = load_max - load_min
    if span <= 0.0:
        span = 1.0
    unit = (load - load_min) / span

    rising = normalised[1:] > normalised[:-1]
    falling = normalised[1:] < normalised[:-1]

    # Fluid pound: the load must rise with the plunger on the upstroke.  The
    # comparison is made on a smoothed trace, because load-cell noise alone
    # produces a negative increment on almost every sample and would otherwise
    # swamp the physical reversal.
    # The smoothing window is chosen long compared with a cushioning ripple
    # period so that the oscillation is attenuated before the derivative is
    # taken, while the sustained collapse of a fluid-pound upstroke survives.
    window = max(5, int(round(len(load) / 12)) | 1)
    smooth = np.convolve(unit, np.ones(window) / window, mode="same")
    offset = max(1, window // 2)
    sustained_drop = np.zeros_like(smooth)
    if len(smooth) > offset:
        sustained_drop[:-offset] = smooth[:-offset] - smooth[offset:]

    # Exclude the two turnarounds (bottom and top dead centre) before taking the
    # maximum.  A healthy card is a *parallelogram*: the standing valve makes the
    # upstroke and downstroke carry different column weights, so the load steps
    # at each reversal.  That step is geometry, not a fault, and measuring the
    # smoothed derivative across it would read every healthy card as fluid
    # pound.  Only the interior of the upstroke, where a genuine supply collapse
    # makes the load fall while the plunger is still rising, is a signal.
    turnarounds = np.zeros_like(rising)
    half = max(1, window)
    rising_index = np.flatnonzero(rising)
    falling_index = np.flatnonzero(falling)
    if rising_index.size and falling_index.size:
        for boundary in (int(rising_index[-1]) + 1, int(falling_index[-1]) + 1):
            if 0 < boundary < len(turnarounds):
                turnarounds[max(0, boundary - half) : min(len(turnarounds), boundary + half)] = True
    interior_rising = rising & ~turnarounds
    reversal = (
        float(np.max(sustained_drop[1:][interior_rising])) if np.any(interior_rising) else 0.0
    )
    reversal = min(max(reversal, 0.0), 1.0)

    # Rod float: departure of the loop from a constant-width parallelogram.
    #
    # Binning by *position* (not by sample index) is what makes this work: the
    # Gibbs solver re-phases the card onto bottom dead centre, so sample order
    # carries no meaning, but matched positions on the two strokes do.
    #
    # A healthy card is a loop of roughly constant width, so the width profile
    # is straight.  Buoyant drag is a depression localised at mid-downstroke, so
    # the profile is bumpy -- and that shape difference survives any loop width,
    # which the plain mean difference could not: a healthy card and a floating
    # rod differ in *how the width varies*, not merely in how wide it is.
    width_profile = _width_profile_residual(normalised, load, rising, falling, span)
    asymmetry = width_profile

    # Pump tagging: excess load at the end of the downstroke.
    end = max(2, len(load) // 25)
    tail = float(np.max(unit[-end:]) - np.mean(unit[-end:]))

    # Gas interference.  A cushioning gas cap produces a *coherent* ripple,
    # whereas load-cell noise is white, so the lag-1 autocorrelation of the
    # detrended load separates the two far more cleanly than its amplitude.
    kernel = np.ones(window) / window
    smoothed = np.convolve(load, kernel, mode="same")
    residual = load - smoothed
    ripple = float(np.std(residual) / span)
    energy = float(np.mean(residual**2))
    if energy > 0.0:
        coherence = float(np.mean(residual[1:] * residual[:-1]) / energy)
    else:
        coherence = 0.0

    # Linearity of the card.  A healthy pump, an unanchored tubing and a
    # mechanical impact all trace a straight-sided parallelogram in
    # (position, load), whereas a cushioning gas cap and a collapsing fluid
    # column do not.  This is the residual discriminator once the specific
    # faults have been ruled out.
    slope, intercept = np.polyfit(normalised, unit, 1)
    residual_fit = unit - (slope * normalised + intercept)
    linearity = float(np.sqrt(np.mean(residual_fit**2)))

    # Unanchored tubing: the load maximum is displaced from top dead centre.
    skew = float(normalised[int(np.argmax(load))] - 1.0)

    return {
        "stroke_m": stroke,
        "load_span_n": span,
        "upstroke_reversal": reversal,
        "downstroke_asymmetry": asymmetry,
        "tail_spike": tail,
        "ripple": ripple,
        "coherence": coherence,
        "linearity": linearity,
        "skew": skew,
        "top_position_fraction": float(normalised[int(np.argmax(load))]),
    }


def analytic_diagnosis(features: Dict[str, float]) -> CardLabel:
    """Rule-based diagnosis from the geometric card features.

    Independent of the network and computed from the same features, so that
    agreement between the two is a genuine cross-check rather than a tautology.
    The order follows the physical hierarchy: a hard mechanical impact outranks
    a fluid-supply problem, which outranks a supply problem.
    """
    if features["tail_spike"] > 0.18:
        return CardLabel.PUMP_TAGGING
    if features["upstroke_reversal"] > 0.10:
        return CardLabel.FLUID_POUND
    # Rod float depresses the *downstroke*, so the downstroke mean falls below
    # the upstroke mean.  Unanchored tubing lags the load, which raises it.
    # The sign of the asymmetry therefore separates the two.
    if features["downstroke_asymmetry"] < -0.08:
        return CardLabel.ROD_FLOATING
    if features["downstroke_asymmetry"] > 0.15:
        return CardLabel.UNANCHORED_TUBING
    if features["linearity"] > 0.06:
        return CardLabel.GAS_INTERFERENCE
    return CardLabel.NORMAL_FULL_BARREL


# ---------------------------------------------------------------------------
# Neural network
# ---------------------------------------------------------------------------


def _torch():
    """Import torch lazily so the physics modules stay torch-free."""
    import torch  # noqa: WPS433  (deliberate lazy import)

    return torch


class DynoCardNet:  # pragma: no cover - replaced below by the torch definition
    """Placeholder replaced by the real torch module in ``_build_net``."""


def _build_net():
    """Construct the residual 1D CNN.  Separated so torch is imported lazily."""
    torch = _torch()
    import torch.nn as nn

    class _ResidualBlock(nn.Module):
        """Two dilated convolutions with a residual connection."""

        def __init__(self, channels: int, dilation: int) -> None:
            super().__init__()
            self.conv1 = nn.Conv1d(
                channels, channels, kernel_size=5, padding=2 * dilation, dilation=dilation
            )
            self.conv2 = nn.Conv1d(channels, channels, kernel_size=5, padding=2, dilation=1)
            self.norm1 = nn.BatchNorm1d(channels)
            self.norm2 = nn.BatchNorm1d(channels)
            self.activation = nn.GELU()

        def forward(self, x):
            residual = x
            out = self.activation(self.norm1(self.conv1(x)))
            out = self.norm2(self.conv2(out))
            return self.activation(out + residual)

    class Network(nn.Module):
        """Residual 1D CNN over the (position, load) card channels."""

        def __init__(self, classes: int = len(CARD_LABELS), width: int = 32) -> None:
            super().__init__()
            self.stem = nn.Sequential(
                nn.Conv1d(2, width, kernel_size=7, padding=3),
                nn.BatchNorm1d(width),
                nn.GELU(),
            )
            self.blocks = nn.Sequential(
                _ResidualBlock(width, dilation=1),
                _ResidualBlock(width, dilation=2),
                _ResidualBlock(width, dilation=4),
            )
            self.head = nn.Sequential(
                nn.AdaptiveAvgPool1d(1),
                nn.Flatten(),
                nn.Linear(width, width),
                nn.GELU(),
                nn.Dropout(0.1),
                nn.Linear(width, classes),
            )

        def forward(self, x):
            features = self.blocks(self.stem(x))
            return self.head(features)

    return Network()


# Bind the lazily built class onto the module namespace.
DynoCardNet = _build_net  # type: ignore[assignment]


# ---------------------------------------------------------------------------
# Classifier wrapper
# ---------------------------------------------------------------------------


@dataclass
class CardPrediction:
    """Outcome of a single card classification."""

    label: CardLabel
    confidence: float
    probabilities: Dict[str, float]
    features: Dict[str, float]
    analytic_label: CardLabel

    @property
    def agrees_with_analytic(self) -> bool:
        """Whether the network and the geometric cross-check agree."""
        return self.label is self.analytic_label

    def as_dict(self) -> dict:
        """JSON-serialisable view for the API layer."""
        return {
            "label": self.label.value,
            "confidence": self.confidence,
            "probabilities": dict(self.probabilities),
            "features": dict(self.features),
            "analytic_label": self.analytic_label.value,
            "agrees_with_analytic": self.agrees_with_analytic,
        }


class DynoCardClassifier:
    """Trained residual 1D CNN wrapper with persistence and analytic cross-check.

    Parameters
    ----------
    weights_path
        Where the trained weights are cached.  If the file is absent the
        network is trained on synthetic cards and the result written here.
    device
        Torch device string; ``"cpu"`` is used for the in-cluster deployment.
    seed
        Seed for reproducible initialisation and training.
    """

    def __init__(
        self,
        weights_path: Optional[Path] = None,
        device: str = "cpu",
        seed: int = 26120,
        train: bool = True,
    ) -> None:
        self.weights_path = Path(weights_path) if weights_path else None
        self.device = device
        self.seed = seed
        torch = _torch()
        torch.manual_seed(seed)
        self.net = _build_net().to(device)
        self.net.eval()
        self.trained = False
        if train and self.weights_path is not None and self.weights_path.exists():
            self.load()
        elif train:
            self.train_and_save(self.weights_path)

    # -- persistence ------------------------------------------------------
    def save(self, path: Optional[Path] = None) -> Path:
        """Write the weights to ``path`` (or the configured path)."""
        target = Path(path) if path else self.weights_path
        if target is None:
            raise ValueError("no weights path configured")
        target.parent.mkdir(parents=True, exist_ok=True)
        torch = _torch()
        torch.save({"state_dict": self.net.state_dict(), "seed": self.seed}, target)
        return target

    def load(self, path: Optional[Path] = None) -> None:
        """Read weights from ``path`` (or the configured path)."""
        source = Path(path) if path else self.weights_path
        if source is None or not source.exists():
            raise FileNotFoundError("no trained weights available")
        torch = _torch()
        payload = torch.load(source, map_location=self.device, weights_only=True)
        self.net.load_state_dict(payload["state_dict"])
        self.net.eval()
        self.trained = True

    # -- training ---------------------------------------------------------
    def train_and_save(
        self,
        path: Optional[Path] = None,
        epochs: int = 26,
        batch_size: int = 64,
        samples_per_label: int = 700,
        validation_fraction: float = 0.15,
        damping_rates: Optional[Sequence[float]] = None,
    ) -> Dict[str, float]:
        """Train the network on synthetic cards and persist the weights.

        The set is split deterministically into training and validation
        partitions, and the returned metrics include the validation accuracy
        and the per-class recall, which the test suite asserts on.

        Parameters
        ----------
        damping_rates
            Sequence of damping rates used to reconstruct surface cards to
            downhole cards during training. If None, a default range covering
            cool to hot reservoir conditions is used. This trains the network
            to be robust across the full operating envelope.
        """
        torch = _torch()
        inputs, targets = build_training_set(
            samples_per_label=samples_per_label, seed=self.seed, damping_rates=damping_rates
        )
        rng = np.random.default_rng(self.seed)
        order = rng.permutation(len(inputs))
        inputs, targets = inputs[order], targets[order]
        split = int(len(inputs) * (1.0 - validation_fraction))
        train_x = torch.from_numpy(inputs[:split])
        train_y = torch.from_numpy(targets[:split])
        val_x = torch.from_numpy(inputs[split:])
        val_y = torch.from_numpy(targets[split:])

        optimiser = torch.optim.AdamW(self.net.parameters(), lr=3e-3, weight_decay=1e-4)
        criterion = torch.nn.CrossEntropyLoss()
        generator = torch.Generator().manual_seed(self.seed)
        loader = torch.utils.data.DataLoader(
            torch.utils.data.TensorDataset(train_x, train_y),
            batch_size=batch_size,
            shuffle=True,
            generator=generator,
        )
        self.net.train()
        last_loss = 0.0
        for _ in range(epochs):
            for batch_x, batch_y in loader:
                optimiser.zero_grad()
                loss = criterion(self.net(batch_x.to(self.device)), batch_y.to(self.device))
                loss.backward()
                optimiser.step()
                last_loss = float(loss.item())
        self.net.eval()

        with torch.no_grad():
            logits = self.net(val_x.to(self.device))
            predictions = logits.argmax(dim=1).cpu().numpy()
        expected = val_y.numpy()
        accuracy = float(np.mean(predictions == expected))
        recall: Dict[str, float] = {}
        for label in CARD_LABELS:
            index = LABEL_INDEX[label]
            mask = expected == index
            recall[label.value] = float(np.mean(predictions[mask] == expected[mask])) if np.any(mask) else 0.0
        metrics = {"validation_accuracy": accuracy, "final_loss": last_loss, **recall}
        self.metrics = metrics
        self.trained = True
        if path is not None or self.weights_path is not None:
            self.save(path)
        return metrics

    # -- inference --------------------------------------------------------
    def predict(
        self,
        position_m: Sequence[float],
        load_n: Sequence[float],
    ) -> CardPrediction:
        """Classify a single card and return the label with its confidence."""
        if not self.trained:
            raise RuntimeError("classifier has not been trained")
        torch = _torch()
        features = card_features(position_m, load_n)
        batch = torch.from_numpy(normalise_card(position_m, load_n)[None, ...]).to(self.device)
        with torch.no_grad():
            logits = self.net(batch)
            probabilities = torch.softmax(logits, dim=1)[0].cpu().numpy()
        index = int(np.argmax(probabilities))
        return CardPrediction(
            label=CARD_LABELS[index],
            confidence=float(probabilities[index]),
            probabilities={
                label.value: float(probabilities[i]) for i, label in enumerate(CARD_LABELS)
            },
            features=features,
            analytic_label=analytic_diagnosis(features),
        )

    def predict_batch(
        self, positions: Sequence[Sequence[float]], loads: Sequence[Sequence[float]]
    ) -> List[CardPrediction]:
        """Classify a batch of cards, batching the network forward pass."""
        if not self.trained:
            raise RuntimeError("classifier has not been trained")
        if len(positions) != len(loads):
            raise ValueError("positions and loads must have the same batch length")
        torch = _torch()
        if not positions:
            return []
        batch = np.stack([normalise_card(p, l) for p, l in zip(positions, loads)])
        with torch.no_grad():
            logits = self.net(torch.from_numpy(batch).to(self.device))
            probabilities = torch.softmax(logits, dim=1).cpu().numpy()
        results: List[CardPrediction] = []
        for i, (position, load) in enumerate(zip(positions, loads)):
            index = int(np.argmax(probabilities[i]))
            features = card_features(position, load)
            results.append(
                CardPrediction(
                    label=CARD_LABELS[index],
                    confidence=float(probabilities[i][index]),
                    probabilities={
                        label.value: float(probabilities[i][j])
                        for j, label in enumerate(CARD_LABELS)
                    },
                    features=features,
                    analytic_label=analytic_diagnosis(features),
                )
            )
        return results


def ensure_weights(
    weights_dir: Path,
    device: str = "cpu",
    seed: int = 26120,
    epochs: int = 26,
    samples_per_label: int = 700,
    damping_rates: Optional[Sequence[float]] = None,
) -> DynoCardClassifier:
    """Load cached weights, or train and cache them on first use.

    This is the on-boot routine: a fresh deployment trains from the
    parametric card model and writes the weights, so no binary checkpoint has
    to be committed.
    """
    target = Path(weights_dir) / "dyno_classifier.pt"
    classifier = DynoCardClassifier(weights_path=target, device=device, seed=seed, train=False)
    if target.exists():
        classifier.load()
        return classifier
    classifier.train_and_save(
        target, epochs=epochs, samples_per_label=samples_per_label, damping_rates=damping_rates
    )
    return classifier
